# Generated by Django 3.1.7 on 2021-04-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cervejas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Origem', models.CharField(max_length=150)),
                ('Alcool', models.IntegerField()),
                ('Familia', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('Tipo', models.CharField(default='', max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='home/images')),
                ('nota', models.IntegerField(default=5)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
    ]
