# Generated by Django 3.1.7 on 2021-04-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='alcool',
            new_name='Alcool',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='estilo',
            new_name='Familia',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='origem',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='Origem',
        ),
        migrations.RemoveField(
            model_name='review',
            name='nota',
        ),
    ]
