# Generated by Django 3.1.7 on 2021-04-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cervejas_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejas',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
