# Generated by Django 3.1.7 on 2021-04-21 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cervejas_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejas',
            name='date_public',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
