# Generated by Django 3.1.7 on 2021-04-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review_tipo_cerveja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='tipo_cerveja',
            new_name='Tipo',
        ),
    ]
