# Generated by Django 3.1.7 on 2021-04-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cervejas_date_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejas',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', upload_to='home/images'),
        ),
    ]
