# Generated by Django 3.1.7 on 2021-04-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210414_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Tipo',
            field=models.CharField(default='', max_length=150),
        ),
    ]
