# Generated by Django 3.1.7 on 2021-04-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210421_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejas',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
