# Generated by Django 3.1.7 on 2021-04-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210414_2035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Cervejas',
        ),
    ]
