# Generated by Django 3.1.7 on 2021-04-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210414_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cervejas',
            old_name='Nome',
            new_name='title',
        ),
    ]
