# Generated by Django 3.1.7 on 2021-04-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210414_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejas',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
