# Generated by Django 3.1.7 on 2021-04-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cervejas_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cervejas',
            name='url',
        ),
        migrations.AlterField(
            model_name='cervejas',
            name='image',
            field=models.ImageField(blank=True, upload_to='home/images'),
        ),
    ]
