# Generated by Django 3.1.7 on 2021-04-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210414_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervejas',
            name='Alcool',
            field=models.IntegerField(),
        ),
    ]
