# Generated by Django 3.1.7 on 2021-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210414_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervejas',
            name='nota',
            field=models.IntegerField(default='5'),
        ),
    ]
